/*
 * Canvas hosts the two cheap rules do not already catch.
 *
 * GENERATED by scripts/build_extension_hosts.py from the app's own
 * institution data. Do not edit by hand: a second copy of this list is
 * exactly the drift this repo keeps paying for, and a test fails when
 * this file stops matching shared/institutions.py.
 *
 * Of 4757 known institutions, a `.instructure.com` suffix and the word
 * "canvas" recognise all but the 100 listed here.
 */

export const CANVAS_HOST_SUFFIX = ".instructure.com";
export const CANVAS_HOST_SUBSTRING = "canvas";

export const CANVAS_HOSTS = new Set([
  "app.pm.hms.harvard.edu",
  "aula.eigvirtual.com",
  "aula.uoc.edu",
  "bruinlearn.ucla.edu",
  "campus.europaeducationgroup.es",
  "campusportalentodigital.fundaciononce.es",
  "catcourses.ucmerced.edu",
  "cientificavirtual.cientifica.edu.pe",
  "clases.imagenpublica.mx",
  "classes.ascham.nsw.edu.au",
  "classroom.galencollege.edu",
  "classroom.sdi.edu",
  "cole2.uconline.edu",
  "courses.ecu.edu.au",
  "courses.evangel.edu",
  "courses.lasell.edu",
  "courses.letu.edu",
  "courses.online.umich.edu",
  "courses.online.usc.edu",
  "courses.sfcollege.edu",
  "courses.tesu.edu",
  "courseworks2.columbia.edu",
  "cpeonline.ucdavis.edu",
  "eagleonline.hccs.edu",
  "ecourses.pvamu.edu",
  "egator.greenriver.edu",
  "elearn.chemeketa.edu",
  "elearn.ciom.edu.au",
  "elearn.sinclair.edu",
  "elearn.ucr.edu",
  "elearning.mines.edu",
  "glow.williams.edu",
  "hub.hw.com",
  "ilearn.laccd.edu",
  "impactonline.ie.edu",
  "instructure.charlotte.edu",
  "ivylearn.ivytech.edu",
  "kodiak.wne.edu",
  "kuconnect.ku.edu",
  "learn.adelaide.edu.au",
  "learn.auckland.ac.nz",
  "learn.bradley.edu",
  "learn.cfainstitute.org",
  "learn.falmouth.ac.uk",
  "learn.insead.edu",
  "learn.kisubischools.org",
  "learn.ontariotechu.ca",
  "learn.providencehigh.org",
  "learn.rave.ac.uk",
  "learn.rcm.ac.uk",
  "learn.sasc.nsw.edu.au",
  "learn.stfrancis.edu",
  "learn.tedi-london.ac.uk",
  "learning.acc.edu.au",
  "learning.avondale.edu.au",
  "learning.curtin.edu.au",
  "learning.eui.eu",
  "learning.flatironschool.com",
  "learning.healthcoachesacademy.com",
  "learning.london.edu",
  "learning.unisg.ch",
  "learning.vlerick.com",
  "learning.yschools.qld.edu.au",
  "learnonline.yu.edu",
  "lms.educationapps.vic.gov.au",
  "lms.griffith.edu.au",
  "lms.hkam.org.hk",
  "lms.learnforlife.sg",
  "lms.neumont.edu",
  "lms.niec.edu.sg",
  "lms.pps.net",
  "lms.sgenable.sg",
  "lms.theolympiaschools.edu.vn",
  "micampus.unir.net",
  "my.ebs.edu",
  "my.uclaextension.edu",
  "myaipm.aipm.edu.au",
  "mycourses.plymouth.edu",
  "mycourses.umhb.edu",
  "mynew.aolcc.ca",
  "myuni.adelaide.edu.au",
  "nuku.wgtn.ac.nz",
  "online.branded-edu.com",
  "online.butlercc.edu",
  "online.dts.edu",
  "online.henley.ac.uk",
  "online.isde.es",
  "online.seminolestate.edu",
  "online.smc.edu",
  "online.voguecollege.com",
  "onlinelearning.scu.edu",
  "q.utoronto.ca",
  "sedeonline.santotomas.cl",
  "study.online.abertay.ac.uk",
  "uclearn.canberra.edu.au",
  "ulwazi.wits.ac.za",
  "usaonline.southalabama.edu",
  "webcampus.unr.edu",
  "webcourses.ucf.edu",
  "worldclassroom.webster.edu",
]);

/** Whether `host` is a Canvas site this extension recognises. */
export function isCanvasHost(host) {
  if (!host) return false;
  const h = String(host).toLowerCase();
  return (
    h.endsWith(CANVAS_HOST_SUFFIX) ||
    h.includes(CANVAS_HOST_SUBSTRING) ||
    CANVAS_HOSTS.has(h)
  );
}
