# Auto-generated by build_windows.py - do not edit manually.
# Regenerated on every build from version.py.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(2, 0, 2, 0),
    prodvers=(2, 0, 2, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x4,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', 'Canvas Downloader'),
         StringStruct('FileDescription', 'Canvas Downloader'),
         StringStruct('FileVersion', '2.0.2'),
         StringStruct('InternalName', 'Canvas Downloader'),
         StringStruct('LegalCopyright', 'Copyright (C) 2026 BrkBuilds - GPL-3.0-or-later'),
         StringStruct('OriginalFilename', 'Canvas Downloader.exe'),
         StringStruct('ProductName', 'Canvas Downloader'),
         StringStruct('ProductVersion', '2.0.2')])
    ]),
    VarFileInfo([VarStruct('Translation', [0x0409, 1200])])
  ]
)
