"""``version.py`` must never be BEHIND, or equal to, the newest shipped tag.

Found by the macOS 15 live audit 2026-08-10: the app was being gated for release
as v2.0.2 while ``version.py`` still said ``2.0.1`` - which is also already a
shipped tag. The sidebar showed the wrong version, but the sharp consequence is
``ui/update_banner.py``: it computes ``_is_newer(github_tag, __version__)``, so
tagging the release v2.0.2 with a 2.0.1 bundle tells **every user of that build,
on every launch, for ever** that an update is available - pointing at the build
they are already running. It cannot self-clear.

Nothing in the build or the suite asserted this, which is the only reason it got
as far as the final gate. The check is deliberately about the ORDER, not about
any particular number: it passes for any version strictly ahead of every tag, so
it never has to be edited when the version moves.

Skips rather than fails when tags are unavailable (a shallow CI clone, or a
source tree with no git), because "I cannot see the tags" is not evidence of a
version mistake.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent


def _version_tuple(s: str) -> tuple[int, ...]:
    """Numeric tuple, mirroring update_banner's own fallback parse."""
    parts: list[int] = []
    for chunk in s.strip().lstrip("vV").split("."):
        digits = "".join(c for c in chunk if c.isdigit())
        if not digits:
            break
        parts.append(int(digits))
    return tuple(parts) or (0,)


def _tags() -> list[str]:
    try:
        r = subprocess.run(["git", "tag"], cwd=REPO, capture_output=True,
                           text=True, timeout=30)
    except Exception:                                           # noqa: BLE001
        return []
    if r.returncode != 0:
        return []
    return [t for t in (r.stdout or "").split() if t.strip()]


def test_version_is_never_behind_a_shipped_tag():
    """version.py may EQUAL the newest tag; it may never be below it.

    RELAXED from strictly-ahead on 2026-08-22, and the evidence is in this very
    file. The property that matters is the one its sibling below asserts through
    the real ``_is_newer``: the banner must not offer an update to the build the
    user is running. At ``version.py == newest tag`` that sibling PASSES, because
    ``_is_newer("2.0.2", "2.0.2")`` is False. Only being BEHIND causes the
    documented harm - which is what this test's own title always said.

    Strictly-ahead asserted something stronger than the harm, and it is
    unsatisfiable during the window that matters: tagging v2.0.2 for a build made
    from ``version.py == 2.0.2`` is the correct and normal state, and the release
    is not finished until its installers are attached. Demanding a bump at the
    moment of tagging would mean the next Windows build stamps 2.0.3 into an
    installer that has to be attached to the v2.0.2 release - the asset/version
    mismatch that `marketing/FINDINGS.md` already records shipping once.

    So: bump version.py when you START the next version, not when you tag the
    current one.
    """
    from version import __version__

    tags = _tags()
    if not tags:
        pytest.skip("no git tags visible (shallow clone or no git) - "
                    "cannot judge the ordering")

    local = _version_tuple(__version__)
    newest = max(tags, key=_version_tuple)
    assert local >= _version_tuple(newest), (
        f"version.py is {__version__!r} but {newest!r} is already tagged. "
        f"Shipping this build would make ui/update_banner.py offer every user "
        f"an update to the release they are running. Bump version.py first.")


def test_the_update_banner_would_not_offer_an_update_to_the_current_build():
    """The consequence, stated as the property that actually matters.

    Asserted through the REAL comparison the banner uses, not a re-implementation
    of it - a copy here would keep passing if `_is_newer` changed underneath.
    """
    from version import __version__
    from ui.update_banner import _is_newer

    tags = _tags()
    if not tags:
        pytest.skip("no git tags visible")

    for tag in tags:
        assert not _is_newer(tag.lstrip("vV"), __version__), (
            f"the update banner would fire for already-shipped tag {tag!r} "
            f"against local version {__version__!r}")


# --- The Windows PE resource must agree with version.py ---------------------
# version_info.py is GENERATED by scripts/build_windows.py, but it is also
# CHECKED IN, and Canvas_Downloader.spec consumes it directly
# (version='version_info.py'). CLAUDE.md documents the Windows build as a bare
# `pyinstaller Canvas_Downloader.spec`, which does NOT regenerate it - so a
# release built the documented way stamps whatever version was last committed.
# Found at 2.0.1 while the app was 2.0.2: Explorer's file properties, and any
# tooling that reads the PE resource, would have reported the previous release.

def test_the_windows_pe_resource_matches_version_py():
    import re
    from version import __version__

    src = (REPO / "version_info.py").read_text(encoding="utf-8")
    major, minor, patch = (int(p) for p in __version__.split(".")[:3])

    tuples = re.findall(r"\((\d+),\s*(\d+),\s*(\d+),\s*(\d+)\)", src)
    assert tuples, "version_info.py has no filevers/prodvers tuple"
    for t in tuples:
        assert tuple(int(x) for x in t[:3]) == (major, minor, patch), (
            f"version_info.py declares {t[:3]} but version.py says {__version__}. "
            "Regenerate it: python -c \"import sys; sys.path.insert(0,'scripts'); "
            "import build_windows; from version import __version__; "
            "build_windows._generate_version_info(__version__)\"")

    assert __version__ in src, (
        f"the FileVersion/ProductVersion strings must read {__version__}")


def test_the_spec_still_consumes_that_file():
    """If the spec stops reading version_info.py this test is measuring nothing."""
    spec = (REPO / "Canvas_Downloader.spec").read_text(encoding="utf-8")
    assert "version='version_info.py'" in spec.replace('"', "'")
