"""Generate the extension's Canvas-host list from the app's own institution data.

Why generated rather than hand-written
--------------------------------------
The extension has to answer one question before it can guide anybody: **is the
tab you are looking at your Canvas?** Getting that wrong in either direction is
a friction bug - telling a student on their own Canvas page that they are in the
wrong place, or offering to sign them in from a page that is not Canvas at all.

The app already knows the answer for 4,757 institutions
(``shared/institutions.py``, itself generated - see
``.claude/rules/institution-picker.md``). A second hand-maintained list in
JavaScript is the "write a rule once" failure this repo pays for more than any
other, so this derives from that one and a test asserts they still agree.

What is actually shipped, and why it is small
---------------------------------------------
Measured against the real list:

* **4,421 of 4,757** hosts are ``<school>.instructure.com``, so one suffix rule
  covers 93% and no data has to ship for them.
* **336** are custom domains, of which **236** contain the word ``canvas``.
* So a suffix rule plus a substring rule reach **97.9%**, and the remaining
  **100** hosts are what this file exists to carry.

Shipping only the exceptions keeps the payload at a few kilobytes instead of
150, and - more importantly - it keeps the file readable, so anyone can see
exactly which sites the extension recognises.

    python scripts/build_extension_hosts.py          # write it
    python scripts/build_extension_hosts.py --check  # fail if it is stale
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from shared.institutions import DATA                 # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'extension', 'canvas-hosts.js')

#: The two rules that need no data. Kept here rather than in the JS so the
#: generator and the extension cannot disagree about what is already covered.
SUFFIX = '.instructure.com'
SUBSTRING = 'canvas'


def exceptional_hosts() -> list[str]:
    """Hosts the two cheap rules do NOT already recognise."""
    out = set()
    for row in DATA:
        host = (row[1] or '').strip().lower()
        if not host:
            continue
        if host.endswith(SUFFIX) or SUBSTRING in host:
            continue
        out.add(host)
    return sorted(out)


def render() -> str:
    hosts = exceptional_hosts()
    total = len(DATA)
    lines = [
        '/*',
        ' * Canvas hosts the two cheap rules do not already catch.',
        ' *',
        ' * GENERATED by scripts/build_extension_hosts.py from the app\'s own',
        ' * institution data. Do not edit by hand: a second copy of this list is',
        ' * exactly the drift this repo keeps paying for, and a test fails when',
        ' * this file stops matching shared/institutions.py.',
        ' *',
        f' * Of {total} known institutions, a `{SUFFIX}` suffix and the word',
        f' * "{SUBSTRING}" recognise all but the {len(hosts)} listed here.',
        ' */',
        '',
        'export const CANVAS_HOST_SUFFIX = "%s";' % SUFFIX,
        'export const CANVAS_HOST_SUBSTRING = "%s";' % SUBSTRING,
        '',
        'export const CANVAS_HOSTS = new Set([',
    ]
    for host in hosts:
        lines.append('  "%s",' % host)
    lines.append(']);')
    lines.append('')
    lines.append('/** Whether `host` is a Canvas site this extension recognises. */')
    lines.append('export function isCanvasHost(host) {')
    lines.append('  if (!host) return false;')
    lines.append('  const h = String(host).toLowerCase();')
    lines.append('  return (')
    lines.append('    h.endsWith(CANVAS_HOST_SUFFIX) ||')
    lines.append('    h.includes(CANVAS_HOST_SUBSTRING) ||')
    lines.append('    CANVAS_HOSTS.has(h)')
    lines.append('  );')
    lines.append('}')
    lines.append('')
    return '\n'.join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog='python scripts/build_extension_hosts.py',
                                 description=__doc__.splitlines()[0])
    ap.add_argument('--check', action='store_true',
                    help='do not write; exit 1 if the file is missing or stale')
    args = ap.parse_args(argv)

    want = render()
    if args.check:
        if not os.path.exists(OUT):
            print(f'  MISSING: {OUT}', flush=True)
            return 1
        with open(OUT, encoding='utf-8') as f:
            have = f.read()
        if have != want:
            print('  STALE: extension/canvas-hosts.js no longer matches '
                  'shared/institutions.py. Run '
                  'python scripts/build_extension_hosts.py', flush=True)
            return 1
        print(f'  up to date ({len(exceptional_hosts())} exceptional hosts)',
              flush=True)
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(want)
    print(f'  wrote {OUT} ({len(exceptional_hosts())} exceptional hosts of '
          f'{len(DATA)} institutions)', flush=True)
    return 0


if __name__ == '__main__':
    sys.exit(main())
