"""
build_windows.py - Single-command Windows release build for Canvas Downloader.

Usage:
    python build_windows.py [--no-installer]

Steps:
  1. Read __version__ from version.py (single source of truth).
  2. Generate version_info.py (PyInstaller PE version resource).
  3. Run pyinstaller Canvas_Downloader.spec.
  4. Run iscc Canvas_Downloader_Setup.iss with /DAppVersion=<version>
     (skipped if --no-installer is passed or ISCC is not found).

Output:
  dist/Canvas Downloader/          - unpacked app
  installer_output/
    Canvas_Downloader_Setup_<ver>.exe  - Inno Setup installer
"""

import importlib.util
import pathlib
import shutil
import subprocess
import sys
import textwrap

ROOT = pathlib.Path(__file__).parent.parent.resolve()


# ── Step 1: Read version ──────────────────────────────────────────

def _read_version() -> str:
    spec = importlib.util.spec_from_file_location("version", ROOT / "version.py")
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.__version__


# ── Step 2: Generate PyInstaller version info file ────────────────

def _generate_version_info(version: str) -> pathlib.Path:
    """Write version_info.py (PyInstaller PE resource format) and return its path."""
    parts = version.split(".")
    # Pad to 4 components for the Windows file-version tuple
    while len(parts) < 4:
        parts.append("0")
    major, minor, patch, build = (int(p) for p in parts[:4])

    content = textwrap.dedent(f"""\
        # Auto-generated by build_windows.py - do not edit manually.
        # Regenerated on every build from version.py.
        VSVersionInfo(
          ffi=FixedFileInfo(
            filevers=({major}, {minor}, {patch}, {build}),
            prodvers=({major}, {minor}, {patch}, {build}),
            mask=0x3f,
            flags=0x0,
            OS=0x4,
            fileType=0x1,
            subtype=0x0,
            date=(0, 0)
          ),
          kids=[
            StringFileInfo([
              StringTable(
                '040904B0',
                [StringStruct('CompanyName', 'Canvas Downloader'),
                 StringStruct('FileDescription', 'Canvas Downloader'),
                 StringStruct('FileVersion', '{version}'),
                 StringStruct('InternalName', 'Canvas Downloader'),
                 StringStruct('LegalCopyright', ''),
                 StringStruct('OriginalFilename', 'Canvas Downloader.exe'),
                 StringStruct('ProductName', 'Canvas Downloader'),
                 StringStruct('ProductVersion', '{version}')])
            ]),
            VarFileInfo([VarStruct('Translation', [0x0409, 1200])])
          ]
        )
    """)

    out = ROOT / "version_info.py"
    out.write_text(content, encoding="utf-8")
    print(f"[build] Generated {out.name} for version {version}")
    return out


# ── Step 3: PyInstaller ───────────────────────────────────────────

def _run_pyinstaller() -> None:
    spec = ROOT / "Canvas_Downloader.spec"
    if not spec.exists():
        sys.exit(f"[build] ERROR: {spec} not found.")
    cmd = [sys.executable, "-m", "PyInstaller", "--clean", str(spec)]
    print(f"[build] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        sys.exit(f"[build] ERROR: PyInstaller exited with code {result.returncode}.")
    print("[build] PyInstaller succeeded.")


# ── Step 4: Inno Setup ────────────────────────────────────────────

def _run_inno(version: str) -> None:
    iss = ROOT / "Canvas_Downloader_Setup.iss"
    if not iss.exists():
        print(f"[build] WARNING: {iss.name} not found - skipping installer build.")
        return

    iscc = shutil.which("iscc") or shutil.which("ISCC")
    if not iscc:
        # Try the default Inno Setup 6 install path
        default = pathlib.Path(r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe")
        if default.exists():
            iscc = str(default)
    if not iscc:
        print(
            "[build] WARNING: ISCC (Inno Setup compiler) not found on PATH.\n"
            "         Install Inno Setup 6 or add it to PATH to build the installer.\n"
            "         Skipping installer step."
        )
        return

    cmd = [iscc, f"/DAppVersion={version}", str(iss)]
    print(f"[build] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        sys.exit(f"[build] ERROR: ISCC exited with code {result.returncode}.")
    print(f"[build] Installer built successfully for version {version}.")


# ── Main ──────────────────────────────────────────────────────────

def main() -> None:
    no_installer = "--no-installer" in sys.argv

    version = _read_version()
    print(f"[build] Building Canvas Downloader v{version} for Windows")

    _generate_version_info(version)
    _run_pyinstaller()

    if no_installer:
        print("[build] --no-installer flag set; skipping Inno Setup step.")
    else:
        _run_inno(version)

    print(f"\n[build] Done. Version {version} built successfully.")


if __name__ == "__main__":
    main()
