"""Generate docs/canvas-url-directory.html - a crawlable list of Canvas URLs.

WHY THIS PAGE EXISTS, and why it is shaped the way it is
--------------------------------------------------------
Instructure already runs "Find My Canvas URL" and a school search on
instructure.com/canvas/login, and they own the head term outright. Checked
2026-08-27: searching for the query returns their tool, their login page and
their KB article, and an institution-specific search returns the university's
own page. We will not outrank either and should not try.

The one thing they do not offer is a **crawlable** list. Their search is
client-rendered, so no hostname is visible text to anything that does not run
JavaScript - which includes several assistant crawlers.

**That makes server-rendered rows the entire point of this build.** A page that
injected its rows with JavaScript would reproduce the competitor's only
weakness and have no reason to exist. Every institution below is in the HTML.
The filter box is added BY the script, so with JavaScript off a visitor gets
the full list rather than a search box that does nothing.

ONE PAGE, NOT 4,757. Google's spam policy defines scaled content abuse as many
pages generated to manipulate rankings rather than to help anyone. A single
filterable list of verified hostnames is a tool. Four thousand pages each
holding one name and one URL is what that policy is about. Do not generate
per-institution pages.

THE DATA is shared/institutions.py, generated by build_institution_list.py.
Every hostname there was proven at generation time to answer
/api/v1/users/self with Canvas's own unauthenticated payload, so it is a live
Canvas host rather than a parked domain or an SSO portal.

NOT GROUPED BY COUNTRY, deliberately: only 1,558 of 4,757 rows have a known
country, so country sections would put 3,199 institutions in an "unknown"
bucket and read as broken. Alphabetical, with the country shown as a chip
where it is known.

THE LIST IS NOT EXHAUSTIVE and the page must keep saying so, exactly as the
in-app picker does. A student whose school is missing must never conclude the
app does not support them.
"""
from __future__ import annotations

import html
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from site_shell import _shell, SITE, OG, OG_ALT  # noqa: E402
from shared.institutions import DATA, COUNT  # noqa: E402

SLUG = "canvas-url-directory.html"
TITLE = "Canvas URL Directory: %s Verified University Canvas Addresses" % f"{COUNT:,}"
DESC = ("A searchable, crawlable list of %s institutions' Canvas login URLs, "
        "each verified live against the Canvas API." % f"{COUNT:,}")
H1 = "Canvas URL directory"
LEDE = ("%s institutions and the Canvas address each one uses, verified live "
        "rather than guessed. Your school works whether or not it is on this "
        "list." % f"{COUNT:,}")

e = html.escape

PAGE_CSS = """
  <style>
    .dir-tools { display: flex; gap: 12px; flex-wrap: wrap; align-items: center;
      margin: 0 0 18px; }
    .dir-count { font-size: 14px; color: var(--txt3); }
    /* Base link colour. Without it a bare <a> falls back to the UA's #0000EE:
       measured 2.08:1 on the "school search" link in the intro, against the
       4.5:1 floor, and three such links on this page. The 4,757 directory
       links are `table.dir td.dir-host a` at (0,2,3) and the nav buttons
       carry their own classes, so all of them beat this (0,0,1) rule -
       verified by diffing every one of the 4,775 anchors' computed colour
       before and after. */
    a { color: var(--cyan); text-decoration: none; }
    a:hover { text-decoration: underline; }
    #dirq { flex: 1 1 260px; min-width: 220px; padding: 10px 14px;
      border-radius: 10px; border: 1px solid rgba(255,255,255,.14);
      background: rgba(255,255,255,.04); color: var(--txt); font: inherit;
      font-size: 15px; }
    /* A border-colour change alone is a weak focus cue - it is the same
       signal hover gives. :focus-visible adds a real ring for keyboard
       users without putting one on every mouse click into the field. */
    #dirq:focus { outline: none; border-color: var(--cyan); }
    #dirq:focus-visible { outline: 2px solid var(--cyan); outline-offset: 2px; }
    .dir-tbl-wrap { overflow-x: auto; border-radius: 12px;
      border: 1px solid rgba(255,255,255,.09); }
    table.dir { width: 100%; border-collapse: collapse; font-size: 14px; }
    table.dir th, table.dir td { padding: 9px 14px; text-align: left;
      border-bottom: 1px solid rgba(255,255,255,.06); vertical-align: top; }
    table.dir th { position: sticky; top: 0; background: #12131c;
      font-size: 12px; letter-spacing: .04em; text-transform: uppercase;
      color: var(--txt3); z-index: 1; }
    table.dir tbody tr:hover { background: rgba(255,255,255,.03); }
    table.dir td.dir-host a { color: var(--cyan); text-decoration: none;
      word-break: break-all; }
    table.dir td.dir-host a:hover { text-decoration: underline; }
    .dir-cc { font-size: 11px; color: var(--txt3); border:
      1px solid rgba(255,255,255,.14); border-radius: 5px; padding: 1px 6px; }
    .dir-none { display: none; padding: 22px 14px; color: var(--txt3); }
    .dir-note { font-size: 14px; color: var(--txt3); margin: 16px 0 0; }
  </style>
"""

# The filter is INJECTED, so a visitor with JavaScript off gets the whole list
# instead of a search box that silently does nothing. It filters on a
# lower-cased name+host string built once, and it never touches the row set -
# rows are only hidden, so the page stays crawlable in every state.
PAGE_JS = """
  <script>
  (function () {
    var tbl = document.getElementById('dirtbl');
    if (!tbl) return;
    var rows = Array.prototype.slice.call(tbl.tBodies[0].rows);
    var keys = rows.map(function (r) { return (r.textContent || '').toLowerCase(); });
    var tools = document.getElementById('dirtools');
    var count = document.getElementById('dircount');
    var none = document.getElementById('dirnone');
    var inp = document.createElement('input');
    inp.type = 'search';
    inp.id = 'dirq';
    inp.placeholder = 'Search %s institutions...';
    inp.setAttribute('aria-label', 'Search institutions');
    tools.insertBefore(inp, tools.firstChild);
    var t = null;
    function apply() {
      var q = inp.value.trim().toLowerCase();
      var shown = 0;
      for (var i = 0; i < rows.length; i++) {
        var hit = !q || keys[i].indexOf(q) !== -1;
        rows[i].style.display = hit ? '' : 'none';
        if (hit) shown++;
      }
      // Explicit locale: bare toLocaleString() follows the BROWSER's, so on a
      // Danish machine the label flipped from the server-rendered "4,757" to
      // "4.757" the moment this script ran. The page is in English and the
      // static half of the label is already formatted that way.
      var fmt = function (x) { return x.toLocaleString('en-US'); };
      count.textContent = shown === rows.length
        ? fmt(rows.length) + ' institutions'
        : fmt(shown) + ' of ' + fmt(rows.length);
      none.style.display = shown ? 'none' : 'block';
    }
    inp.addEventListener('input', function () {
      if (t) clearTimeout(t);
      t = setTimeout(apply, 90);
    });
  })();
  </script>
"""


def rows_html() -> str:
    out = []
    for name, host, cc, _flags in DATA:
        cc = (cc or "").strip()
        chip = '<span class="dir-cc">%s</span>' % e(cc) if cc else ""
        # No data-k attribute: it duplicated the name and host that are
        # already in the cells, and measured 281 KB of the 1.24 MB page. The
        # filter builds its key from row.textContent instead, which is the
        # same string for free.
        out.append(
            '        <tr><td>%s %s</td>'
            '<td class="dir-host"><a href="https://%s" rel="nofollow noopener" '
            'target="_blank">%s</a></td></tr>'
            % (e(name), chip, e(host), e(host)))
    return "\n".join(out)


def build() -> pathlib.Path:
    css, nav, foot, tail = _shell()
    url = SITE + SLUG
    ld = """{
  "@context": "https://schema.org",
  "@graph": [
    {"@type": "WebSite", "@id": "%s#website", "url": "%s",
     "name": "Canvas Downloader", "inLanguage": "en"},
    {"@type": "CollectionPage", "@id": "%s#page", "url": "%s",
     "name": %s, "description": %s,
     "isPartOf": {"@id": "%s#website"}, "inLanguage": "en"},
    {"@type": "BreadcrumbList", "@id": "%s#crumbs", "itemListElement": [
      {"@type": "ListItem", "position": 1, "name": "Home", "item": "%s"},
      {"@type": "ListItem", "position": 2, "name": "Canvas URL directory", "item": "%s"}
    ]}
  ]
}""" % (SITE, SITE, url, url, _j(TITLE), _j(DESC), SITE, url, SITE, url)

    page = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{e(TITLE)}</title>
  <meta name="description" content="{e(DESC)}" />
  <link rel="canonical" href="{url}" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{url}" />
  <meta property="og:title" content="{e(TITLE)}" />
  <meta property="og:description" content="{e(DESC)}" />
  <meta property="og:image" content="{OG}" />
  <meta property="og:image:alt" content="{e(OG_ALT)}" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="{e(TITLE)}" />
  <meta name="twitter:description" content="{e(DESC)}" />
  <meta name="twitter:image" content="{OG}" />
  <script type="application/ld+json">
{ld}
  </script>
  <meta name="theme-color" content="#0b0c14" />
  <link rel="icon" type="image/x-icon" href="icon.ico" />
  <link rel="apple-touch-icon" href="icon.png" />
  <link rel="preload" as="font" type="font/woff2" href="assets/fonts/inter-latin.woff2" crossorigin />
  <link rel="stylesheet" href="fonts.css" />
{css}
{PAGE_CSS}
</head>
<body>
{nav}

  <main>

  <div class="hero">
    <div class="container wide">
      <h1>{H1}</h1>
      <p class="sub">{e(LEDE)}</p>
    </div>
  </div>

  <div class="container wide">
    <div class="art">
      <p>Every address below was checked against the Canvas API at the time the
      list was generated, so each one is a live Canvas host rather than a
      university home page or a sign-in portal that merely mentions Canvas.
      The list is generated from the same data the app uses for its own login
      picker.</p>

      <p><strong>This list is not exhaustive, and a missing school is not an
      unsupported one.</strong> Canvas is used by many thousands of
      institutions; this covers the largest and best known. If yours is not
      here, it still works everywhere a Canvas URL is asked for, including in
      this app. Instructure also runs its own
      <a href="https://www.instructure.com/canvas/login" rel="nofollow noopener"
      target="_blank">school search</a>, which is the authoritative source and
      worth trying if this page does not have you.</p>

      <div class="dir-tools" id="dirtools">
        <span class="dir-count" id="dircount">{COUNT:,} institutions</span>
      </div>

      <div class="dir-tbl-wrap">
        <table class="dir" id="dirtbl">
          <thead>
            <tr><th>Institution</th><th>Canvas URL</th></tr>
          </thead>
          <tbody>
{rows_html()}
          </tbody>
        </table>
        <div class="dir-none" id="dirnone">No institution here matches that.
        Your school's Canvas address still works - ask your IT help desk, or
        try Instructure's own school search linked above.</div>
      </div>

      <p class="dir-note">Country is shown where it could be established from
      the address or the institution's own name. A blank one means unknown
      rather than anything about the institution.</p>

      <p>If you want this list as a file rather than a page, the same rows are
      published as <a href="canvas-data.html">CSV and
      JSON under CC BY 4.0</a>, with the verification method and the field
      notes beside them.</p>

      <h2 id="what-next">What to do with your Canvas URL</h2>

      <p>It is what every Canvas tool asks for first, including the mobile app
      and this one. Paired with an access token it is enough to reach your own
      courses through the Canvas API, which is how anything downloads your
      material. There is more on what a token is, and what it cannot do, in
      <a href="canvas-access-token-explained.html">what a Canvas access token
      is</a>.</p>

      <p>If you are here because you are trying to get your course material off
      Canvas, the practical routes are compared in
      <a href="how-to-download-all-canvas-files.html">how to download all your
      files from Canvas</a>.</p>
    </div>
  </div>

  </main>

{foot}

{tail}{PAGE_JS % f"{COUNT:,}"}
</body>
</html>
"""
    out = DOCS / SLUG
    out.write_text(page, encoding="utf-8", newline="\r\n")
    return out


def _j(s: str) -> str:
    import json
    return json.dumps(s)


if __name__ == "__main__":
    p = build()
    kb = p.stat().st_size / 1024
    print("  %s  %d institutions  %.1f KB" % (p.name, COUNT, kb))
