"""Curated seeds for ``scripts/build_institution_list.py``.

(name, ISO 3166-1 alpha-2 country) for well-known institutions worldwide,
weighted toward the app's live markets (Australia, India, wider Asia, Africa,
the Nordics) alongside the US, UK and Europe.

These are SEEDS, not the shipped list: each is looked up against Instructure's
public account finder and kept only if a confident match exists AND that domain
verifies as a live Canvas host. Many seeds here are deliberately never shipped -
plenty of big universities do not use Canvas at all, and a seed that finds
nothing is a correct outcome, not a gap to force.

The seed name is what the picker DISPLAYS, so it is written the way a student
would say it rather than the way the Canvas account happens to be titled
("University of Melbourne", not "The University of Melbourne (non-SSO)").
"""

SEEDS: list[tuple[str, str]] = [
    # --- Denmark / Nordics ---------------------------------------------
    ("Copenhagen Business School", "DK"), ("University of Copenhagen", "DK"),
    ("Aarhus University", "DK"), ("Aalborg University", "DK"),
    ("Technical University of Denmark", "DK"), ("University of Southern Denmark", "DK"),
    ("Roskilde University", "DK"), ("IT University of Copenhagen", "DK"),
    ("VIA University College", "DK"), ("Copenhagen School of Design and Technology", "DK"),
    ("Zealand Business College", "DK"), ("Danmarks Medie- og Journalisthojskole", "DK"),
    ("University of Oslo", "NO"), ("Norwegian University of Science and Technology", "NO"),
    ("University of Bergen", "NO"), ("BI Norwegian Business School", "NO"),
    ("UiT The Arctic University of Norway", "NO"), ("University of Agder", "NO"),
    ("University of Stavanger", "NO"), ("OsloMet", "NO"), ("Nord University", "NO"),
    ("Norwegian School of Economics", "NO"), ("Norwegian University of Life Sciences", "NO"),
    ("Uppsala University", "SE"), ("Lund University", "SE"), ("Stockholm University", "SE"),
    ("KTH Royal Institute of Technology", "SE"), ("Chalmers University of Technology", "SE"),
    ("University of Gothenburg", "SE"), ("Linkoping University", "SE"), ("Umea University", "SE"),
    ("Karolinska Institutet", "SE"), ("Stockholm School of Economics", "SE"), ("Malmo University", "SE"),
    ("University of Helsinki", "FI"), ("Aalto University", "FI"), ("Tampere University", "FI"),
    ("University of Turku", "FI"), ("University of Oulu", "FI"), ("University of Jyvaskyla", "FI"),
    ("University of Iceland", "IS"), ("Reykjavik University", "IS"),
    # --- Australia / NZ -------------------------------------------------
    ("University of Melbourne", "AU"), ("University of Sydney", "AU"),
    ("University of New South Wales", "AU"), ("Australian National University", "AU"),
    ("University of Queensland", "AU"), ("Monash University", "AU"),
    ("University of Western Australia", "AU"), ("University of Adelaide", "AU"),
    ("University of Technology Sydney", "AU"), ("RMIT University", "AU"),
    ("Macquarie University", "AU"), ("Deakin University", "AU"), ("Griffith University", "AU"),
    ("Curtin University", "AU"), ("Queensland University of Technology", "AU"),
    ("La Trobe University", "AU"), ("University of Wollongong", "AU"),
    ("University of Newcastle", "AU"), ("Flinders University", "AU"),
    ("University of Tasmania", "AU"), ("Swinburne University of Technology", "AU"),
    ("Western Sydney University", "AU"), ("Edith Cowan University", "AU"),
    ("James Cook University", "AU"), ("Charles Sturt University", "AU"),
    ("University of Canberra", "AU"), ("Murdoch University", "AU"),
    ("University of South Australia", "AU"), ("Victoria University", "AU"),
    ("Bond University", "AU"), ("Australian Catholic University", "AU"),
    ("University of Auckland", "NZ"), ("University of Otago", "NZ"),
    ("Victoria University of Wellington", "NZ"), ("University of Canterbury", "NZ"),
    ("Massey University", "NZ"), ("University of Waikato", "NZ"),
    ("Auckland University of Technology", "NZ"),
    # --- India ----------------------------------------------------------
    ("Indian Institute of Technology Bombay", "IN"), ("Indian Institute of Technology Delhi", "IN"),
    ("Indian Institute of Technology Madras", "IN"), ("Indian Institute of Technology Kanpur", "IN"),
    ("Indian Institute of Technology Kharagpur", "IN"), ("Indian Institute of Technology Roorkee", "IN"),
    ("Indian Institute of Technology Guwahati", "IN"), ("Indian Institute of Technology Hyderabad", "IN"),
    ("Indian Institute of Science", "IN"), ("Indian Institute of Management Ahmedabad", "IN"),
    ("Indian Institute of Management Bangalore", "IN"), ("Indian Institute of Management Calcutta", "IN"),
    ("Ashoka University", "IN"), ("Amity University", "IN"), ("Manipal Academy of Higher Education", "IN"),
    ("Vellore Institute of Technology", "IN"), ("BITS Pilani", "IN"), ("Shiv Nadar University", "IN"),
    ("Jindal Global University", "IN"), ("SRM Institute of Science and Technology", "IN"),
    ("University of Delhi", "IN"), ("Jawaharlal Nehru University", "IN"), ("Anna University", "IN"),
    ("Christ University", "IN"), ("Symbiosis International University", "IN"),
    ("Indian School of Business", "IN"), ("Krea University", "IN"), ("Plaksha University", "IN"),
    # --- Asia -------------------------------------------------------------
    ("National University of Singapore", "SG"), ("Nanyang Technological University", "SG"),
    ("Singapore Management University", "SG"), ("Singapore University of Technology and Design", "SG"),
    ("University of Hong Kong", "HK"), ("Chinese University of Hong Kong", "HK"),
    ("Hong Kong University of Science and Technology", "HK"), ("City University of Hong Kong", "HK"),
    ("Hong Kong Polytechnic University", "HK"), ("Hong Kong Baptist University", "HK"),
    ("University of Tokyo", "JP"), ("Kyoto University", "JP"), ("Waseda University", "JP"),
    ("Keio University", "JP"), ("Osaka University", "JP"), ("Tohoku University", "JP"),
    ("Seoul National University", "KR"), ("Korea University", "KR"), ("Yonsei University", "KR"),
    ("KAIST", "KR"), ("Sungkyunkwan University", "KR"),
    ("Peking University", "CN"), ("Tsinghua University", "CN"), ("Fudan University", "CN"),
    ("Zhejiang University", "CN"), ("Shanghai Jiao Tong University", "CN"),
    ("Duke Kunshan University", "CN"), ("NYU Shanghai", "CN"),
    ("National Taiwan University", "TW"), ("National Tsing Hua University", "TW"),
    ("University of Malaya", "MY"), ("Universiti Kebangsaan Malaysia", "MY"),
    ("Universiti Putra Malaysia", "MY"), ("Universiti Sains Malaysia", "MY"),
    ("Universiti Teknologi Malaysia", "MY"), ("Taylors University", "MY"), ("Sunway University", "MY"),
    ("Monash University Malaysia", "MY"),
    ("University of the Philippines", "PH"), ("Ateneo de Manila University", "PH"),
    ("De La Salle University", "PH"), ("University of Santo Tomas", "PH"),
    ("Universitas Indonesia", "ID"), ("Institut Teknologi Bandung", "ID"),
    ("Universitas Gadjah Mada", "ID"), ("Bina Nusantara University", "ID"),
    ("Chulalongkorn University", "TH"), ("Mahidol University", "TH"), ("Thammasat University", "TH"),
    ("Vietnam National University", "VN"), ("RMIT Vietnam", "VN"), ("Fulbright University Vietnam", "VN"),
    ("University of Dhaka", "BD"), ("BRAC University", "BD"), ("North South University", "BD"),
    ("Lahore University of Management Sciences", "PK"), ("Aga Khan University", "PK"),
    ("National University of Sciences and Technology", "PK"),
    # --- Africa / Middle East --------------------------------------------
    ("University of Cape Town", "ZA"), ("University of the Witwatersrand", "ZA"),
    ("Stellenbosch University", "ZA"), ("University of Pretoria", "ZA"),
    ("University of Johannesburg", "ZA"), ("University of KwaZulu-Natal", "ZA"),
    ("North-West University", "ZA"), ("Rhodes University", "ZA"), ("University of the Free State", "ZA"),
    ("Nelson Mandela University", "ZA"), ("University of the Western Cape", "ZA"),
    ("University of Lagos", "NG"), ("University of Ibadan", "NG"), ("Covenant University", "NG"),
    ("Obafemi Awolowo University", "NG"), ("Ahmadu Bello University", "NG"),
    ("American University of Nigeria", "NG"), ("Lagos Business School", "NG"),
    ("University of Nairobi", "KE"), ("Strathmore University", "KE"), ("Kenyatta University", "KE"),
    ("United States International University Africa", "KE"),
    ("University of Ghana", "GH"), ("Kwame Nkrumah University of Science and Technology", "GH"),
    ("Ashesi University", "GH"),
    ("Makerere University", "UG"), ("University of Rwanda", "RW"),
    ("African Leadership University", "RW"), ("University of Dar es Salaam", "TZ"),
    ("American University in Cairo", "EG"), ("Cairo University", "EG"), ("Ain Shams University", "EG"),
    ("University of Botswana", "BW"), ("University of Namibia", "NA"), ("University of Zimbabwe", "ZW"),
    ("United Arab Emirates University", "AE"), ("American University of Sharjah", "AE"),
    ("Khalifa University", "AE"), ("Zayed University", "AE"), ("American University in Dubai", "AE"),
    ("King Abdullah University of Science and Technology", "SA"), ("King Saud University", "SA"),
    ("King Fahd University of Petroleum and Minerals", "SA"), ("Prince Sultan University", "SA"),
    ("Qatar University", "QA"), ("Hamad Bin Khalifa University", "QA"),
    ("Tel Aviv University", "IL"), ("Hebrew University of Jerusalem", "IL"), ("Technion", "IL"),
    ("American University of Beirut", "LB"), ("Bogazici University", "TR"), ("Koc University", "TR"),
    ("Sabanci University", "TR"), ("Middle East Technical University", "TR"),
    # --- United Kingdom / Ireland -----------------------------------------
    ("University of Oxford", "GB"), ("University of Cambridge", "GB"),
    ("Imperial College London", "GB"), ("University College London", "GB"),
    ("London School of Economics and Political Science", "GB"), ("Kings College London", "GB"),
    ("University of Edinburgh", "GB"), ("University of Manchester", "GB"),
    ("University of Bristol", "GB"), ("University of Warwick", "GB"), ("University of Glasgow", "GB"),
    ("University of Leeds", "GB"), ("University of Birmingham", "GB"), ("University of Sheffield", "GB"),
    ("University of Nottingham", "GB"), ("University of Southampton", "GB"),
    ("Durham University", "GB"), ("University of York", "GB"), ("Lancaster University", "GB"),
    ("University of Exeter", "GB"), ("University of Bath", "GB"), ("Newcastle University", "GB"),
    ("Cardiff University", "GB"), ("Queens University Belfast", "GB"), ("University of Liverpool", "GB"),
    ("University of Reading", "GB"), ("University of Sussex", "GB"), ("University of Surrey", "GB"),
    ("University of Aberdeen", "GB"), ("University of St Andrews", "GB"), ("University of Strathclyde", "GB"),
    ("Heriot-Watt University", "GB"), ("Loughborough University", "GB"),
    ("Queen Mary University of London", "GB"), ("City University of London", "GB"),
    ("Birkbeck University of London", "GB"), ("SOAS University of London", "GB"),
    ("Royal Holloway University of London", "GB"), ("Coventry University", "GB"),
    ("Northumbria University", "GB"), ("University of Portsmouth", "GB"),
    ("Nottingham Trent University", "GB"), ("Manchester Metropolitan University", "GB"),
    ("University of Westminster", "GB"), ("Open University", "GB"),
    ("Trinity College Dublin", "IE"), ("University College Dublin", "IE"),
    ("University College Cork", "IE"), ("University of Galway", "IE"), ("Dublin City University", "IE"),
    ("Maynooth University", "IE"),
    # --- Europe (rest) ------------------------------------------------------
    ("Delft University of Technology", "NL"), ("University of Amsterdam", "NL"),
    ("Utrecht University", "NL"), ("Leiden University", "NL"), ("Erasmus University Rotterdam", "NL"),
    ("Wageningen University", "NL"), ("Eindhoven University of Technology", "NL"),
    ("University of Groningen", "NL"), ("Maastricht University", "NL"), ("Radboud University", "NL"),
    ("Vrije Universiteit Amsterdam", "NL"), ("University of Twente", "NL"), ("Tilburg University", "NL"),
    ("ETH Zurich", "CH"), ("EPFL", "CH"), ("University of Zurich", "CH"), ("University of Geneva", "CH"),
    ("University of St Gallen", "CH"), ("University of Bern", "CH"), ("University of Basel", "CH"),
    ("Technical University of Munich", "DE"), ("Ludwig Maximilian University of Munich", "DE"),
    ("Heidelberg University", "DE"), ("Humboldt University of Berlin", "DE"),
    ("Free University of Berlin", "DE"), ("RWTH Aachen University", "DE"),
    ("University of Freiburg", "DE"), ("University of Gottingen", "DE"), ("University of Hamburg", "DE"),
    ("Karlsruhe Institute of Technology", "DE"), ("University of Cologne", "DE"),
    ("Technical University of Berlin", "DE"), ("University of Mannheim", "DE"),
    ("University of Vienna", "AT"), ("Vienna University of Technology", "AT"),
    ("University of Innsbruck", "AT"), ("Vienna University of Economics and Business", "AT"),
    ("KU Leuven", "BE"), ("Ghent University", "BE"), ("Universite Libre de Bruxelles", "BE"),
    ("University of Antwerp", "BE"), ("UCLouvain", "BE"),
    ("Sorbonne University", "FR"), ("Universite PSL", "FR"), ("Sciences Po", "FR"),
    ("Ecole Polytechnique", "FR"), ("HEC Paris", "FR"), ("INSEAD", "FR"),
    ("Universite Paris-Saclay", "FR"), ("Grenoble Alpes University", "FR"),
    ("University of Barcelona", "ES"), ("Autonomous University of Barcelona", "ES"),
    ("Complutense University of Madrid", "ES"), ("Autonomous University of Madrid", "ES"),
    ("Pompeu Fabra University", "ES"), ("IE University", "ES"), ("ESADE", "ES"),
    ("Universidad Carlos III de Madrid", "ES"), ("Universitat Politecnica de Valencia", "ES"),
    ("Polytechnic University of Milan", "IT"), ("Sapienza University of Rome", "IT"),
    ("University of Bologna", "IT"), ("Bocconi University", "IT"), ("University of Padua", "IT"),
    ("University of Milan", "IT"), ("University of Lisbon", "PT"), ("University of Porto", "PT"),
    ("Nova University Lisbon", "PT"), ("Catholic University of Portugal", "PT"),
    ("University of Warsaw", "PL"), ("Jagiellonian University", "PL"),
    ("Warsaw University of Technology", "PL"),
    ("Charles University", "CZ"), ("Czech Technical University in Prague", "CZ"),
    ("Eotvos Lorand University", "HU"), ("Central European University", "HU"),
    ("University of Ljubljana", "SI"), ("University of Zagreb", "HR"),
    ("National and Kapodistrian University of Athens", "GR"),
    ("Aristotle University of Thessaloniki", "GR"),
    ("University of Cyprus", "CY"), ("University of Malta", "MT"), ("University of Luxembourg", "LU"),
    ("University of Tartu", "EE"), ("Tallinn University of Technology", "EE"),
    ("University of Latvia", "LV"), ("Vilnius University", "LT"),
    # --- Canada -------------------------------------------------------------
    ("University of Toronto", "CA"), ("University of British Columbia", "CA"),
    ("McGill University", "CA"), ("University of Alberta", "CA"), ("McMaster University", "CA"),
    ("University of Waterloo", "CA"), ("Western University", "CA"), ("Queens University", "CA"),
    ("University of Calgary", "CA"), ("University of Ottawa", "CA"), ("Dalhousie University", "CA"),
    ("Simon Fraser University", "CA"), ("University of Victoria", "CA"), ("York University", "CA"),
    ("Concordia University", "CA"), ("Carleton University", "CA"), ("University of Manitoba", "CA"),
    ("University of Saskatchewan", "CA"), ("Universite de Montreal", "CA"), ("Universite Laval", "CA"),
    ("Toronto Metropolitan University", "CA"), ("University of Guelph", "CA"),
    # --- Latin America --------------------------------------------------------
    ("University of Sao Paulo", "BR"), ("State University of Campinas", "BR"),
    ("Federal University of Rio de Janeiro", "BR"),
    ("Pontifical Catholic University of Rio de Janeiro", "BR"),
    ("Fundacao Getulio Vargas", "BR"), ("Insper", "BR"),
    ("National Autonomous University of Mexico", "MX"), ("Tecnologico de Monterrey", "MX"),
    ("Universidad Iberoamericana", "MX"), ("Universidad de las Americas Puebla", "MX"),
    ("Pontificia Universidad Catolica de Chile", "CL"), ("University of Chile", "CL"),
    ("Universidad de los Andes", "CO"), ("Universidad Nacional de Colombia", "CO"),
    ("Universidad EAFIT", "CO"), ("Pontificia Universidad Javeriana", "CO"),
    ("University of Buenos Aires", "AR"), ("Universidad Torcuato Di Tella", "AR"),
    ("Pontificia Universidad Catolica del Peru", "PE"), ("Universidad San Francisco de Quito", "EC"),
    ("University of Costa Rica", "CR"), ("University of Puerto Rico", "PR"),
    # --- United States ---------------------------------------------------------
    ("Harvard University", "US"), ("Stanford University", "US"),
    ("Massachusetts Institute of Technology", "US"), ("Yale University", "US"),
    ("Princeton University", "US"), ("Columbia University", "US"), ("University of Chicago", "US"),
    ("University of Pennsylvania", "US"), ("Cornell University", "US"), ("Brown University", "US"),
    ("Dartmouth College", "US"), ("Duke University", "US"), ("Northwestern University", "US"),
    ("Johns Hopkins University", "US"), ("Vanderbilt University", "US"), ("Rice University", "US"),
    ("Emory University", "US"), ("Georgetown University", "US"), ("Carnegie Mellon University", "US"),
    ("New York University", "US"), ("Boston University", "US"), ("Northeastern University", "US"),
    ("University of Southern California", "US"), ("Tufts University", "US"),
    ("University of Notre Dame", "US"), ("Washington University in St Louis", "US"),
    ("California Institute of Technology", "US"), ("University of Rochester", "US"),
    ("Case Western Reserve University", "US"), ("Brandeis University", "US"),
    ("University of California Berkeley", "US"), ("University of California Los Angeles", "US"),
    ("University of California San Diego", "US"), ("University of California Davis", "US"),
    ("University of California Irvine", "US"), ("University of California Santa Barbara", "US"),
    ("University of California Santa Cruz", "US"), ("University of California Riverside", "US"),
    ("University of Michigan", "US"), ("University of Virginia", "US"),
    ("University of North Carolina at Chapel Hill", "US"), ("University of Florida", "US"),
    ("University of Texas at Austin", "US"), ("University of Washington", "US"),
    ("University of Wisconsin Madison", "US"), ("University of Illinois Urbana-Champaign", "US"),
    ("Georgia Institute of Technology", "US"), ("Ohio State University", "US"),
    ("Pennsylvania State University", "US"), ("Purdue University", "US"),
    ("University of Maryland", "US"), ("University of Minnesota", "US"),
    ("University of Colorado Boulder", "US"), ("University of Arizona", "US"),
    ("Arizona State University", "US"), ("Michigan State University", "US"),
    ("Indiana University", "US"), ("University of Iowa", "US"), ("University of Utah", "US"),
    ("Utah State University", "US"), ("Brigham Young University", "US"),
    ("University of Oregon", "US"), ("Oregon State University", "US"),
    ("University of Georgia", "US"), ("Texas A&M University", "US"),
    ("University of Pittsburgh", "US"), ("Rutgers University", "US"),
    ("University of Massachusetts Amherst", "US"), ("University of Connecticut", "US"),
    ("Florida State University", "US"), ("University of Miami", "US"),
    ("University of Alabama", "US"), ("Auburn University", "US"), ("Clemson University", "US"),
    ("University of South Carolina", "US"), ("University of Tennessee", "US"),
    ("University of Kentucky", "US"), ("University of Missouri", "US"),
    ("University of Kansas", "US"), ("University of Nebraska Lincoln", "US"),
    ("University of Oklahoma", "US"), ("Oklahoma State University", "US"),
    ("University of Arkansas", "US"), ("Louisiana State University", "US"),
    ("Colorado State University", "US"), ("Boise State University", "US"),
    ("University of Nevada Las Vegas", "US"), ("University of New Mexico", "US"),
    ("University of Hawaii", "US"), ("University of Alaska", "US"),
    ("Virginia Tech", "US"), ("North Carolina State University", "US"),
    ("University of Delaware", "US"), ("University of Vermont", "US"),
    ("University of New Hampshire", "US"), ("University of Rhode Island", "US"),
    ("Syracuse University", "US"), ("University at Buffalo", "US"),
    ("Stony Brook University", "US"), ("Binghamton University", "US"),
    ("Temple University", "US"), ("Drexel University", "US"), ("Villanova University", "US"),
    ("George Washington University", "US"), ("American University", "US"),
    ("Howard University", "US"), ("Baylor University", "US"),
    ("Southern Methodist University", "US"), ("Texas Tech University", "US"),
    ("University of Houston", "US"), ("University of North Texas", "US"),
    ("University of Central Florida", "US"), ("Florida International University", "US"),
    ("University of South Florida", "US"), ("Georgia State University", "US"),
    ("San Diego State University", "US"), ("San Jose State University", "US"),
    ("California State University Fullerton", "US"), ("California State University Long Beach", "US"),
    ("California Polytechnic State University", "US"), ("Portland State University", "US"),
    ("Western Governors University", "US"), ("Southern New Hampshire University", "US"),
    ("Liberty University", "US"), ("Grand Canyon University", "US"),
    ("DePaul University", "US"), ("Loyola University Chicago", "US"),
    ("University of Denver", "US"), ("Marquette University", "US"),
    ("Wake Forest University", "US"), ("Lehigh University", "US"),
    ("Rensselaer Polytechnic Institute", "US"), ("Worcester Polytechnic Institute", "US"),
    ("Rochester Institute of Technology", "US"), ("Illinois Institute of Technology", "US"),
    ("Stevens Institute of Technology", "US"), ("Colorado School of Mines", "US"),
    ("Wellesley College", "US"), ("Amherst College", "US"), ("Williams College", "US"),
    ("Swarthmore College", "US"), ("Pomona College", "US"), ("Middlebury College", "US"),
    ("Bowdoin College", "US"), ("Carleton College", "US"), ("Oberlin College", "US"),
    ("Smith College", "US"), ("Vassar College", "US"), ("Colgate University", "US"),
    ("Santa Monica College", "US"), ("Miami Dade College", "US"),
    ("Houston Community College", "US"), ("Northern Virginia Community College", "US"),
    ("Salt Lake Community College", "US"), ("Austin Community College", "US"),
]
